In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
churn=pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
churn.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
churn.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
churn.shape

(10000, 14)

In [ ]:
churn.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
cont= churn[churn.Exited == 0]
leave = churn[churn.Exited == 1]

In [ ]:
print(cont.shape)
print(leave.shape)

(7963, 14)
(2037, 14)

In [ ]:
cont.EstimatedSalary.describe()

count      7963.000000
mean      99738.391772
std       57405.586966
min          90.070000
25%       50783.490000
50%       99645.040000
75%      148609.955000
max      199992.480000
Name: EstimatedSalary, dtype: float64

In [ ]:
leave.EstimatedSalary.describe()

count      2037.000000
mean     101465.677531
std       57912.418071
min          11.580000
25%       51907.720000
50%      102460.840000
75%      152422.910000
max      199808.100000
Name: EstimatedSalary, dtype: float64

In [ ]:
churn.groupby('Exited').mean()

<ipython-input-14-65b76d046350>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  churn.groupby('Exited').mean()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
Exited,,,,,,,,,,
0,5024.694964,1.569117e+07,651.853196,37.408389,5.033279,72745.296779,1.544267,0.707146,0.554565,99738.391772
1,4905.917526,1.569005e+07,645.351497,44.837997,4.932744,91108.539337,1.475209,0.699067,0.360825,101465.677531

In [ ]:
churn.value_counts()

RowNumber  CustomerId  Surname     CreditScore  Geography  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
1          15634602    Hargrave    619          France     Female  42   2       0.00       1              1          1               101348.88        1         1
6671       15667932    Bellucci    758          Spain      Female  43   10      0.00       2              1          1               55313.44         0         1
6664       15766185    She         850          Germany    Male    31   4       146587.30  1              1          1               89874.82         0         1
6665       15667632    Birdseye    703          France     Female  42   7       0.00       2              0          1               72500.68         0         1
6666       15599024    Hope        506          Spain      Male    32   8       0.00       2              0          1               182692.80        0         1
                                                                                                                                                               ..
3334       15599078    Yang        619          Germany    Female  41   5       92467.58   1              1          0               38270.47         0         1
3335       15702300    Walker      671          France     Male    27   5       0.00       2              0          0               120893.07        0         1
3336       15660735    T'ang       581          Spain      Female  31   6       0.00       2              1          0               188377.21        0         1
3337       15671390    Chukwukere  690          Spain      Male    36   10      0.00       2              1          0               55902.93         0         1
10000      15628319    Walker      792          France     Female  28   4       130142.79  1              1          0               38190.78         0         1
Length: 10000, dtype: int64

In [ ]:
cont_sample = cont.sample(n=7963)

In [ ]:
new = pd.concat([cont_sample, leave], axis=0)

In [ ]:
new.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8699,8700,15684469,Hsiung,841,Germany,Male,32,2,117070.21,1,1,0,113482.20,0
4710,4711,15685653,Benson,585,Germany,Female,40,3,162261.01,2,1,0,137028.51,0
8656,8657,15791342,Johnston,660,Spain,Male,31,1,84560.04,1,1,1,137784.25,0
2252,2253,15604782,Tan,733,Germany,Female,33,7,187257.94,1,0,1,190430.81,0
8143,8144,15609058,Wan,676,France,Male,23,1,107787.47,1,0,1,116378.82,0

In [ ]:
new.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

In [ ]:
new['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
new.groupby('Exited').mean()

<ipython-input-22-525f64806e0f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  new.groupby('Exited').mean()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
Exited,,,,,,,,,,
0,5024.694964,1.569117e+07,651.853196,37.408389,5.033279,72745.296779,1.544267,0.707146,0.554565,99738.391772
1,4905.917526,1.569005e+07,645.351497,44.837997,4.932744,91108.539337,1.475209,0.699067,0.360825,101465.677531

In [ ]:
x = new.drop(columns=['Surname','RowNumber','NumOfProducts','Geography','Gender','Tenure','Exited'], axis=1)
y = new['Exited']

In [ ]:
print(x)

      CustomerId  CreditScore  Age    Balance  HasCrCard  IsActiveMember  \
8699    15684469          841   32  117070.21          1               0
4710    15685653          585   40  162261.01          1               0
8656    15791342          660   31   84560.04          1               1
2252    15604782          733   33  187257.94          0               1
8143    15609058          676   23  107787.47          0               1
...          ...          ...  ...        ...        ...             ...
9981    15672754          498   42  152039.70          1               1
9982    15768163          655   46  137145.12          1               0
9991    15769959          597   53   88381.21          1               0
9997    15584532          709   36       0.00          0               1
9998    15682355          772   42   75075.31          1               0

      EstimatedSalary
8699        113482.20
4710        137028.51
8656        137784.25
2252        190430.81
8143        116378.82
...               ...
9981         53445.17
9982        115146.40
9991         69384.71
9997         42085.58
9998         92888.52

[10000 rows x 7 columns]

In [ ]:
print(y)

8699    0
4710    0
8656    0
2252    0
8143    0
       ..
9981    1
9982    1
9991    1
9997    1
9998    1
Name: Exited, Length: 10000, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify=y, random_state=2)

In [ ]:
print(x.shape, x_train.shape, x_test.shape)

(10000, 7) (8000, 7) (2000, 7)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [ ]:
print('accuracy on training data: ',training_data_accuracy)

accuracy on training data:  0.79625

In [ ]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [ ]:
print('accuracy on test data: ',test_data_accuracy)

accuracy on test data:  0.7965